### PR TITLE
Adding project description to readme 

### PR DESCRIPTION
**Pull request by Samoo7a**
Please review and feedback

### CODE REVIEW

**Review by MrTim — APPROVED** [review]
Approved but you have a merge conflict :)

**Comment by keponk** [comment]
Looks like you just got your first conflict file :) 
I suspect this might be due to you creating this file README.md twice, once in the master branch *and* commiting it, and then on the Review1 and also commiting it.

If you want later with more time we can confirm and clarify why this happened. :+1:

**Comment by Samoo7a** [comment]
> Looks like you just got your first conflict file :)
> I suspect this might be due to you creating this file README.md twice, once in the master branch _and_ commiting it, and then on the Review1 and also commiting it.
> 
> If you want later with more time we can confirm and clarify why this happened. 👍

I think it is because I had comitted to master initially, and then realized I need to make a branch which has the differences, so deleted and added .... created a bit of frankensteins monster ... 

But yes, I would like to understand more the impact, as still git confuses me for some reason .... so more discussions would always be good :) Thanks

**Comment by Samoo7a** [comment]
> Approved but you have a merge conflict :)

Overachieving :D

**Pull request merged**
